ALTER TABLE assets RENAME COLUMN label TO symbol;
ALTER TABLE assets DROP COLUMN status;
DROP TYPE asset_statuses;
CREATE TYPE asset_status AS ENUM ('asset_status_open', 'asset_status_resolved', 'asset_status_refunded');
ALTER TABLE assets ADD COLUMN status asset_status DEFAULT 'asset_status_open' NOT NULL;
ALTER TABLE markets ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE markets DROP COLUMN status;
DROP TYPE market_statuses;
CREATE TYPE market_status AS ENUM ('market_status_draft', 'market_status_open', 'market_status_closed', 'market_status_resolved', 'market_status_refunded');
ALTER TABLE markets ADD COLUMN status market_status DEFAULT 'market_status_draft' NOT NULL;
