ALTER TABLE admins ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE assets ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE categories ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE holdings ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE markets ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE transactions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE users ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE wallets ALTER COLUMN id SET DEFAULT uuidv7();
