ALTER TABLE passkeys ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL;
ALTER TABLE passkeys ADD COLUMN last_used_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL;
ALTER TABLE passkeys ADD COLUMN name TEXT DEFAULT 'not named' NOT NULL;
